### ISSUE TITLE
Get an ASN dataset (and store in a repo as a data package)

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#1]
Data source:

`curl https://stat.ripe.net/data/country-resource-list/data.json?resource=at`

Documentation: https://stat.ripe.net/docs/data_api#CountryResourceStats

Probably store as a Tabular Data Package in its own dedicated repo.

**Comment by aaronkaplan** [comment]
Also JSON - both are valuable

**Comment by rufuspollock** [comment]
@aaronkaplan it would be useful to get this for work on frontend. Do you know who will lead on scraping this and what the ETA is?

**Comment by aaronkaplan** [comment]
Hi, yes I could automate fetching this . However the better person for that would be @chorsley actually.

**Comment by aaronkaplan** [comment]
Done. Check out this repo: https://github.com/cybergreen-net/reference_data
Would be happy if you guys can make a data package out of it.

**Comment by chorsley** [comment]
For future reference, ftp://ftp.ripe.net/pub/stats/ contains historical info for all RIRs, could be used for both geolocation (accuracy compared to Maxmind?) and ASNs. Would need a good amount of processing and merging before use, however.
