### ISSUE TITLE
clean up old tables in the RDS DB. (was: country codes ("UK") are sometimes upper case, sometimes lower case in the DB)

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/pm#101]
Make this always upper case please.

**Comment by zelima** [comment]
@aaronkaplan Could you please be more exact here? Where in DB, which tables? 
cause running query
`SELECT count(*) FROM fact_count WHERE country!=UPPER(country);`
Gives no results

Plus country codes column has Foreign-key relation with `dim_country` table and it would simply error when creating that `constraint`, if that would be a case

**Comment by aaronkaplan** [comment]
Country table :)

That's a minor thing btw. 

---
Mobile

**Comment by zelima** [comment]
We don't use country table any  more, but `dim_country` where codes are uppercased
Closing as FIXED

**Comment by aaronkaplan** [comment]
Well, if the table is there but it is not used it is not FIXED.
Changing the subject line to "clean up old tables in the RDS DB" then.

This is important to deliver a clean and lean product.

**Comment by zelima** [comment]
FIXED. All unused tables are dropped

**Comment by aaronkaplan** [comment]
thanks, confirmed :)
