### ISSUE TITLE
Data issues: NTP

### ISSUE THREAD

**Issue by chorsley** [cybergreen-net/pm#11]
The following filtering possibilities with NTP data have been observed so far:
- [ ] Amplification factor not taken into account yet, though we do have the byte count of responses to help us here.
- [ ] ["stratum" value in NTP data](https://en.wikipedia.org/wiki/Network_Time_Protocol#Clock_strata) might tell us how intentionally the server is designed to be used for public consumption. A value of 16 is unsynchronised (read: completely unreliable) and possibly unintentionally available.

**Comment by rufuspollock** [comment]
@chorsley suggest we merge this with #18 - wdyt?

**Comment by chorsley** [comment]
Sure - adding above points into #18  and closing this.
