### ISSUE TITLE
Logging platform selection

### ISSUE THREAD

**Issue by chorsley** [cybergreen-net/pm#12]
Requirements for logging:
- Centralised logging in cloud or distributed systems
- Ability to log locally if desired, rather than remote provider
- Ideally, alerting built in (if a logging platform)
- Ability to alert on thresholds (e.g. error volume) or conditions
- Granularity for severity, source, category etc.
- Dashboard for metric (e.g. parsing failures per hour)

**Comment by chorsley** [comment]
Early candidates: 
- https://www.datadoghq.com/ ($15 / host / month, no volume limit?)
- https://aws.amazon.com/cloudwatch/

**Comment by aaronkaplan** [comment]
I recommend abstracting the logging into two parts:
- logging for info/debug/warning etc purposes (-> use python default logger )
- logging for performance monitoring. (-> simply go for datadoghq for the moment. It's OKay'ed by mgmt).

**Comment by rufuspollock** [comment]
@aaronkaplan @chorsley what's the status here?

Can this be pushed out beyond Sep 30?

**Comment by chorsley** [comment]
We've settled on Cloudwatch and Datadog.
