### ISSUE TITLE
Acquistion of Risk Logfile Data for beta 2

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#13]
Data is acquired and is on Aaron's private machine. <del>on S3 private bucket</del>

Check an item once we have the logfile data **and** uploaded to s3 private bucket.
- [x] OpenNTP
- [x] OpenDNS
- [x] Spam
- [x] SNMP
- [x] SSDP

**Comment by chorsley** [comment]
Does this have overlap with #8 ? Is the distinction to have full datasets under #8 , or for these to be generated with ETLv2?

**Comment by rufuspollock** [comment]
@chorsley i'm confused this is issue #13 ...

**Comment by chorsley** [comment]
@rgrp whoops, edited to be #8.

**Comment by rufuspollock** [comment]
@chorsley sort of. This is the "raw" data being up in the bitstore. Not the cleaned the data.
