### ISSUE TITLE
Clean Raw Data: OpenDNS

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#17]
This should run AWS.
- [x] Fetch and uncompress
- [x] Sample (?) - maybe at rate 1
- [x] Clean - filter
- [x] Parse - put into standard internal format

Extras:
- [ ] test harnesses for all or some of this

**Comment by chorsley** [comment]
More info about methodology at https://www.nanog.org/sites/default/files/tue.lightning3.open_resolver.mauch_.pdf.

Issues to date with the open DNS resolver data and how we deal with it:
- [ ] Currently not accounting for RCODE: a value of 5 indicates the query was refused, for example.
- [ ] Currently not accounting for potential volume of amplification. We currently don't have bytes returned to do this, however.
