### ISSUE TITLE
Clean Raw Data: OpenNTP

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#18]
This should run AWS.
- [x] Fetch and uncompress
- [x] Sample (?) - maybe at rate 1
- [x] Clean - filter
- [x] Parse - put into standard internal format

**Comment by chorsley** [comment]
The following filtering possibilities with NTP data have been observed so far:
- [ ] Amplification factor not taken into account yet, though we do have the byte count of responses to help us here.
- [ ] ["stratum" value in NTP data](https://en.wikipedia.org/wiki/Network_Time_Protocol#Clock_strata) might tell us how intentionally the server is designed to be used for public consumption. A value of 16 is unsynchronised (read: completely unreliable) and possibly unintentionally available.

**Comment by chorsley** [comment]
Closing as data can be processed via ETLv2. Further issues at #48 (processing issues due to file size) and #49 (ideas for further filtering).
