### ISSUE TITLE
Produce aggregate data from clean, enriched disaggregated data

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#20]
- [x] Produce `entries.csv`
  - The lowest level of granularity is week
  - How do we handle same IP turning up for same risk in same week: ignore - only count once (?) - see #42 
  - Do we slice by risk for entries.csv? No.

```
risk,time,place,asn,count
openntp,2016-08-01,au,00016,10
```

**Comment by aaronkaplan** [comment]
re: same IP turning up in the same risk in the same week -> ignore. It gets deduped

**Comment by rufuspollock** [comment]
This is DONE. However we do need to check on full dataset when we get it.

**Comment by GregoryRhysEvans** [comment]
This is done. Download links for:
- entry.csv: http://bits-cybergreen-net.s3-website-eu-west-1.amazonaws.com/dev/aggregated/latest/entry000
- place.csv: http://bits-cybergreen-net.s3-website-eu-west-1.amazonaws.com/dev/aggregated/latest/place000
- risk.csv: http://bits-cybergreen-net.s3-website-eu-west-1.amazonaws.com/dev/aggregated/latest/risk000

**Comment by GregoryRhysEvans** [comment]
Note, CSVs will want renaming. See [the issue on the aggregator](https://github.com/cybergreen-net/aggregator/issues/3)
