### ISSUE TITLE
Proposal: dev wiki setup

### ISSUE THREAD

**Issue by chorsley** [cybergreen-net/pm#23]
I'd like to propose establishing a planning / dev wiki here on the pm repo. It would incorporate some of the GDocs we have floating around.

This would primarily be for spec drafts in development. Official, public docs would live somewhere else.

**Comment by rufuspollock** [comment]
@chorsley +1 on point of getting docs here into a repo. Only suggestion would be to use repo itself rather than bother with the wiki e.g. create a directory /doc/ and start populating it.

**Comment by aaronkaplan** [comment]
@chorsley I prefer a regular doc/ folder as well with markdown text

**Comment by chorsley** [comment]
@rgrp @aaronkaplan Yep, no problem having it part of the repo. I've added a docs dir now - please close this issue if I can get a +1 for this approach.

**Comment by rufuspollock** [comment]
FIXED.
