### ISSUE TITLE
Set up RDS database for frontend

### ISSUE THREAD

**Issue by GregoryRhysEvans** [cybergreen-net/pm#26]
- [x] Deploy in AWS console
- [x] Attach IP if necessary

**Comment by rufuspollock** [comment]
@GregoryRhysEvans can this be marked as fixed? We may need to redeploy to eu-west but that can be done in another issue i think.

**Comment by GregoryRhysEvans** [comment]
@rgrp OK, we can mark this as done and do the redeploy separately.
