### ISSUE TITLE
Heroku account for CyberGreen for frontend deployment

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#27]
@YurieIto @aaronkaplan we recommend using heroku to deploy the frontend.

Can you sign up for an heroku account. It is free for now and means we will be ready when we need to do the proper deploy.

**Comment by aaronkaplan** [comment]
@rgrp First I want to see that this runs also locally. It's a _must_.
Sorry. I insist that this can run locally on any web server.

To be clear: I was thinking of some kind of deploy.py script as we had before with the old stats site and docs on prerequisites (packages, nodeJS, etc).

**Comment by rufuspollock** [comment]
@aaronkaplan it can be run locally. Its a node js app. There will be full docs (and there are already on how to run locally).

Having built a lot of these apps i really recommend deploy to heroku. However, I leave it up to you as to how you decide ultimately to deploy.

For go live in September I would request we use heroku as it will be very quick and sysadmin-less to deploy new versions (git push and less than 30s). If you want to set up a server and run the nodejs app locally, config nginx etc etc that's great too 😄

**Comment by aaronkaplan** [comment]
Re: " it can be run locally." Good!
That's important for me.
As long as we are 100% sure we can always run on a local instance on a standard off the shelf Debian/Ubuntu server, I am fine with having it run on heroku as well.

**Comment by ataslim** [comment]
@rgrp heroku account created with a temporary PW. Let me know the best way to get that information to you.

**Comment by rufuspollock** [comment]
FIXED. @ataslim i or @GregoryRhysEvans can message you on skype.
