### ISSUE TITLE
Enable MFA for all AWS users

### ISSUE THREAD

**Issue by chorsley** [cybergreen-net/pm#29]
All users with AWS access should have multi-factor authentication (MFA) enabled for their accounts. Instructions using Google Authenticator or similar at:

http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_enable_virtual.html

**Comment by chorsley** [comment]
@rgrp could you please arrange this for yourself and your colleagues?

**Comment by rufuspollock** [comment]
@chorsley can we postpone this to the end of next week. We will get on this, however behind other items.

**Comment by aaronkaplan** [comment]
@rgrp Are you guys ready for that? It's really simple, just download the google authenticator and click "enable MFA" on AWS.

**Comment by GregoryRhysEvans** [comment]
@aaronkaplan We are ready, but we have one team member who does not have a smartphone. Are there alternatives to using the app?

**Comment by chorsley** [comment]
@GregoryRhysEvans A few options are listed at https://aws.amazon.com/iam/details/mfa/. Perhaps SMS is an option?

**Comment by GregoryRhysEvans** [comment]
Fixed. @rgrp and myself have MFA enabled. @zelima does not own a smartphone and is in the process of getting the SMS service working; but does not need access to the console in the interim in any case.
