### ISSUE TITLE
bits.cybergreen.net as a website bucket

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#30]

**Comment by chorsley** [comment]
Now available to public at https://s3-eu-west-1.amazonaws.com/bits-cybergreen-net/prod/index.html and https://s3-eu-west-1.amazonaws.com/bits-cybergreen-net/dev/index.html.

We can lock down access to /dev/ to authed AWS users - not quite as streamlined a process as might be desired. Not sure if that's wanted yet, but we can reopen this / open a new ticket as needed.

**Comment by rufuspollock** [comment]
@chorsley great - and can we get it at http://bits.cybergreen.net?

**Comment by rufuspollock** [comment]
@chorsley ping ... when i visit http://bits.cybergreen.net/ i guess "no such bucket".

**Comment by rufuspollock** [comment]
@GregoryRhysEvans has taken this back on at @chorsley request  (as of Monday).

**Comment by GregoryRhysEvans** [comment]
This bucket is up and the files are publicly available, for example [to download the country data](https://s3-eu-west-1.amazonaws.com/bits.cybergreen.net/stats/latest/country000)
