### ISSUE TITLE
Automate AWS infrastructure deployment

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#33]
Automate all of above (probably using terraform)
- [ ] S3
- [ ] Redshift
- [ ] RDS
- [ ] Lambda

**Comment by aaronkaplan** [comment]
is this a duplicate of another one?

**Comment by rufuspollock** [comment]
FIXED / DUPLICATE. Either done or now in https://github.com/cybergreen-net/infrastructure/issues
