### ISSUE TITLE
Create test harness for ETL process

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#35]
- [ ] ...

**Comment by rufuspollock** [comment]
@chorsley how is this doing /cc @aaronkaplan 

What are the steps involved?

**Comment by chorsley** [comment]
We have some basic test coverage, but this needs expansion. By the time we have things public mid week, we should have decent coverage on each ETL phase.

**Comment by chorsley** [comment]
Complete for this milestone - more expansion down the track.
