### ISSUE TITLE
www.cybergreen.net - final improvements and go live

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#36]
- [x] Final fixes
- [ ] Change DNS
- [ ] Old site moved to old.cybergreen.net (may need to liase with secure decisions)

**Comment by aaronkaplan** [comment]
need exact info for chaning DNS

**Comment by rufuspollock** [comment]
@YurieIto we have made most of the changes - we will put this up and then you can review and give ok on go live. We won't change DNS or anything until then.

**Comment by rufuspollock** [comment]
We have done fixes however waiting on content improvements from @ataslim 

Changing owner to @ataslim 

Looks like this will be delayed until ~ Sep 30th so changing milestone.

**Comment by rufuspollock** [comment]
@YurieIto gave approval for go live yesterday /cc @ataslim 

@aaronkaplan can you notify Moto-san and we initiate change.

**Comment by rufuspollock** [comment]
This is all done at our end modulo a CNAME change once DNS switches over.

@aaronkaplan any ETA from @motok (@motok feel free to jump in yourself here!)

**Comment by motok** [comment]
Hi, what can I do for you?
You've already have;

> bits            IN      CNAME   bits-cybergreen-net.s3.amazonaws.com.
> private.bits    IN      CNAME   private-bits-cybergreen-net.s3.amazonaws.com.

And please tell me if you need additional RRs.

**Comment by rufuspollock** [comment]
@motok we need www.cybergreen.net to change to point to our github pages repo as per instructions at:

https://help.github.com/articles/using-a-custom-domain-with-github-pages/
https://help.github.com/articles/setting-up-a-www-subdomain/

CNAME and ANAME should be to:

```
cybergreen-net.github.io.
```

We want both apex domain and www to point - i.e. www.cybergreen.net and cybergreen.net if possible - the former does require an ANAME record.

**Comment by aaronkaplan** [comment]
@rgrp just for the record: there is no ANAME record type  (pun intended).
See: https://en.wikipedia.org/wiki/List_of_DNS_record_types
And: http://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml
There are proprietary extensions to rrtypes - and I assume ANAME is such a beast. 
But it's not an official rrtype. So, I guess Bind will not support it.
So far only DNS Made Easy seems to implement the ANAME rrtype.

--> summary: Nope!

We will only point "www.cybergreen.net" via CNAME to `cybergreen-net.github.io.`
No Apex domain tricks pls.

**Comment by motok** [comment]
browser access to http://cybergreen-net.github.io/ is now 404 not found.
are you sure to point www to this web site?

**Comment by motok** [comment]
@rgrp : I don't quite understand your request... are you saying;

>  www IN CNAME cybergreen-net.github.io.

thanks.

**Comment by rufuspollock** [comment]
@motok yes - i want to www CNAME to i.e. `cybergreen-net.github.io.`. Right now it won't show anything. Did you see the docs about how github pages hosting works? Basically, one you point to that github servers will take care of serving the right site.

**Comment by rufuspollock** [comment]
@aaronkaplan fine with me if you don't want the root domain - just common practise nowadays (or at least to redirect to www). Anyway, if we have www working that is good.

**Comment by rufuspollock** [comment]
@motok i've updated CNAME on site to work https://github.com/cybergreen-net/inventory.cybergreen.net/blob/gh-pages/CNAME

@aaronkaplan / @ataslim note that inventory.cybergreen.net will now be down.

**Comment by motok** [comment]
I see, and found it is name based virtual host and respond for Host: www.cybergreen.net.
I have just update the DNS entry for www.cybergreen.net as CNAME to cybergreen-net.github.io.

thanks.

**Comment by motok** [comment]
@rgrp would you please check the links in Data Inventory?
the link to openresolverproject.org (and all others I think) is not working.
Thank you!

**Comment by rufuspollock** [comment]
@motok the links are broken because they are wrong in the csv ;-) - see https://github.com/cybergreen-net/inventory.cybergreen.net/issues/34

**Comment by rufuspollock** [comment]
FIXED. It is live ...
