### ISSUE TITLE
Test documentation

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#38]
Test documentation: https://docs.google.com/a/atomatic.net/document/d/1qYBMuPrqD4PMbnpMSv2ZW_6DnnVMah5N5oMuIdDD5vc/edit?usp=sharing
- [ ] Write a brief summary <del>@ataslim </del> Cosive,Atomatic,Aaron
- [x] ETL tests - Cosive - #35 
- [x] Frontend tests - Atomatic [DONE] - https://github.com/cybergreen-net/stats-new/tree/master/tests  
- [ ] write-up of steps done for the frontend tests - Atomatic
- [x] Aggregator tests (?) - Atomatic [DONE] - will be published once we publish repo
- [ ] write-up of steps done for the aggregator tests - Atomatic
- [x] Combine ETL test methodology into common test document @chorsley

**Comment by ataslim** [comment]
@rgrp i'm not familiar with the code on the frontend test link so writing the summary may be a bit of a challenge for me. we'll either need to have a call on this so i can get a better understanding or this would need to be done by someone at atomatic i think.

**Comment by rufuspollock** [comment]
@ataslim can you get a briefing from @YurieIto and @aaronkaplan on what you need here? I would imagine a short one page with a link to test directories might be sufficient ...

**Comment by aaronkaplan** [comment]
> On 27 Sep 2016, at 18:03, Rufus Pollock notifications@github.com wrote:
> 
> @ataslim can you get a briefing from @YurieIto on what you need here? I would imagine a short one page with a link to test directories might be sufficient ...

We'll handle that one together. @rgrp, me and @chorsley  will work on this.

Best,
a.

**Comment by rufuspollock** [comment]
I spoke with Yurie about this today and have booted a doc.

**Comment by chorsley** [comment]
Added ETL section.

**Comment by aaronkaplan** [comment]
was submitted.
