### ISSUE TITLE
aggregation: please count every IP only once within an interval

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/pm#42]
When aggregating (let's say the time window is 1 week), please only count every IP address once for a given risk/ASN/time window.

This is not ideal, there are a number of mistakes (such as DHCP churn) here, but ... it is better than overshooting in our data when it comes to counting the same IP multiple times due to scanning intervals.

In other words:

``` SQL
SELECT 
   COUNT(distinct(ip)) as cnt,time_window as week,ASN 
FROM $table
WHERE ...
GROUP BY week,ASN
ORDER BY ...
```

Note: this is a Sept-30th fix. We will need to revisit that topic later on again.

**Comment by aaronkaplan** [comment]
so can this one be closed then as well?

**Comment by rufuspollock** [comment]
@zelima please close if you think this is fixed.

**Comment by zelima** [comment]
This is fixed see commit: https://github.com/cybergreen-net/aggregator/commit/36e93917388aa0e45a9554bad0a68ea454fc5e42
@aaronkaplan @rgrp I can not close issues here

**Comment by rufuspollock** [comment]
FIXED.
