### ISSUE TITLE
allow for other geolocation lookup DBs

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/pm#43]
- [x] Please take a look at how to replace maxmind by [ip2location](http://lite.ip2location.com/).
- [x] Compare the results / hit rate / accuracy and document it (and or link to accuracy comparisons)
- [x] If satisfactory, re-run the data with ip2location
- [ ] If satisfied with ip2location, consider commercial version.

In any case, please make it configurable which geolocation DB is to be used.

Reminder: we need to be able to make **historic** ip 2 country lookups!

**Comment by chorsley** [comment]
Also see #2 .

**Comment by rufuspollock** [comment]
@aaronkaplan @chorsley is this not a post sep 30 item? Seems not urgent and not super important if we have a working system currently ...

**Comment by chorsley** [comment]
We have already implemented ip2location - coverage seems more complete than MaxMind. Currently not configurable, but would be fairly easy to do so if there was demand.

I can't see historical databases available for download - but nor could I readily for Maxmind. I'm asking if they make these available, or we just start collecting from today on.

**Comment by aaronkaplan** [comment]
I moved this to post sept 30. However - it does touch one issue pre-Sept 30: speed.
the maxmind lookups are slow (if I remember correctly). Would be interesting to know if ip2location is faster (and if so, how many lookups/sec)?

**Comment by chorsley** [comment]
Update on historical references - asked the ip2location vendor, and they don't readily provide historical versions of their database. We'd need to collect them from today to build our own historical repo. I'd reckon that's acceptable given our emphasis on current and future data, but happy to hear dissenting opinions.

**Comment by kxyne** [comment]
ip2location is faster than maxmind and uses less ram. It all depends on hardware obviously but considering we're chewing ~6gb a week I'm not worried about speed, it's the difference between 10 minutes and 15 if we spend thousands of dollars of time on optimising it we'll never see that back. Maxmind to ip2location was a big speed shift for very little work but past that we're really getting into reinventing the wheel.

**Comment by kxyne** [comment]
It needs the plumbing on the ETL side to fetch the right file from git and a cron to store them but otherwise it all seems good.
https://github.com/cybergreen-net/ip2location-historical

**Comment by aaronkaplan** [comment]
cool!

So, what I still found out  - just now... RIPE has that actually. They already solved the historic (maxmind) IP geolocation data issue.
Take a look [here](https://stat.ripe.net/docs/data_api#Geoloc) and [here](https://stat.ripe.net/docs/data_api#GeolocHistory). I don't know if it's possible to download the DB tough for offline calculations.

Anyway, we should state in the /place (a.k.a country) page that any geolocation was done via ip2location

**Comment by kxyne** [comment]
Thought I'd closed this off. The ripe DB doesn't seem to be available and even if we could get it, it would be painful to try to query at any decent speed with historical parameters.
