### ISSUE TITLE
Upload code to github

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/pm#44]
Please do not forget to upload any AWS code (**without any hardcoded passwords**) into the proper github repository.

**Comment by aaronkaplan** [comment]
Same is valid for the etl2 code, ping @chorsley , @kxyne -> please make a PR when appropriate.

**Comment by rufuspollock** [comment]
@aaronkaplan all frontend code is live. Aggregator code is held back whilst we do check to ensure no sensitive information e.g. db passwords in there. Will be live this week.

**Comment by aaronkaplan** [comment]
> On 26 Sep 2016, at 10:39, Rufus Pollock notifications@github.com wrote:
> 
> @aaronkaplan all frontend code is live. Aggregator code is held back whilst we do check to ensure no sensitive information e.g. db passwords in there. Will be live this week.

Cool, thanks!

**Comment by chorsley** [comment]
Quick update on ETLv2 - have a couple of AWS-related bits to separate out into env variables, should have it released publicly by mid-week.

**Comment by GregoryRhysEvans** [comment]
Aggregator code is uploaded to repo with instructions for use. See: https://github.com/cybergreen-net/aggregator/issues/5

**Comment by rufuspollock** [comment]
Nothing left for Atomatic here.

**Comment by chorsley** [comment]
ETLv2 now lives at https://github.com/cybergreen-net/etl2
