### ISSUE TITLE
NTP data issue with disk size

### ISSUE THREAD

**Issue by chorsley** [cybergreen-net/pm#48]
NTP data extracts at maximum to over 81GB, and the disk volume size on EC2 instance much smaller, so a good number of dates fail at the moment. Need to find a workaround - change image config, or reduce size of files we need to handle ahead of ETL.

**Comment by aaronkaplan** [comment]
is this still an issue? If so, any news on this?

**Comment by chorsley** [comment]
Fixed, will close. The container data volume size was increased to handle files of this size.
