### ISSUE TITLE
Choose an cloud infrastructure config option and use it

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#50]
I'd recommend terraform based on research and some (limited) experience.

https://www.terraform.io/

**Comment by aaronkaplan** [comment]
Whatever the choice is finally, please remember that a hard requirement is that any type of software we use MUST (as in RFC MUST) smoothly work _locally_ (off-cloud).

Vagrant, Chef, Puppet would fulfill this requirement.
No idea if terraform does that.

**Comment by rufuspollock** [comment]
@aaronkaplan terraform is specifically for setting up cloud infrastructure. Puppet, chef, ansible, salt etc are different: they are for configuring deployed machines (mainly). Terraform is built by people who built vagrant - but has a different purpose.

**Comment by aaronkaplan** [comment]
---

Mobile

> On 30.09.2016, at 08:26, Rufus Pollock notifications@github.com wrote:
> 
> @aaronkaplan terraform is specifically for setting up cloud infrastructure. Puppet, chef, ansible, salt etc are different: they are for configuring deployed machines (mainly). Terraform is built by people who built vagrant - but has a different purpose.

Thx for the quick info. 
Reminder: everything MUST be able to be run non-cloud(ed) as well.

**Comment by rufuspollock** [comment]
@aaronkaplan terraform is a tool for booting the cloud infrastructure. It would not be relevant for local install.

**Comment by aaronkaplan** [comment]
any news on this?

**Comment by rufuspollock** [comment]
DUPLICATE and FIXED. See https://github.com/cybergreen-net/infrastructure/issues/7
