### ISSUE TITLE
cybergreen.net to direct to www

### ISSUE THREAD

**Issue by chorsley** [cybergreen-net/pm#52]
For ease of use, entering "cybergreen.net" in a browser should redirect to www.cybergreen.net.

**Comment by rufuspollock** [comment]
@chorsley i agree and have flagged this to @aaronkaplan but @aaronkaplan indicated this was maybe not needed (plus issues with apex domains and DNS).

**Comment by aaronkaplan** [comment]
@rgrp nope. I meant something else. Apex domains don't work as described in heroku docs for standard name servers. There is no record type for that in DNS. It's a custom extension. Hence we won't have apex domains. That is a very very specific thing for heroku it seems.
Standard web servers don't have that issue and I can easily do a http redirect there.

-> see also  #53 . It's connected. If we solve #53, this is very easy.

**Comment by zelima** [comment]
FIXED. Try [cybergreen.net](http://cybergreen.net)
