### ISSUE TITLE
HTTPS errors on www.cybergreen.net

### ISSUE THREAD

**Issue by chorsley** [cybergreen-net/pm#53]
Accessing https://www.cybergreen.net/ gives SSL cert errors. The common name in the cert has been issued for github.com and related sites, not cybergreen.net.

Should verify cert status, or reconfigure if present.

![image](https://cloud.githubusercontent.com/assets/383615/19623999/d2c4dc2e-991d-11e6-9fe5-eb2ad43c0e7f.png)

**Comment by rufuspollock** [comment]
AFAICT there is no easy way to set up https properly on github custom domains 😦   - see e.g. https://github.com/isaacs/github/issues/156. We can use cloudflare or similar or we could move to gitlab which seems to support this.

**Comment by aaronkaplan** [comment]
Yurie has a new CERT. It needs to be installed on the info site's config via Atomatic. 

---

Mobile

**Comment by rufuspollock** [comment]
@aaronkaplan and @ataslim i think this is a priority to fix somehow or other since it is a very poor UX to get certificate warnings on your main website. We have two options:
- Investigate using cloudflare proxy option - https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/
- Move the deployed webiste somewhere else where we can have ssl - this will involve some work to build site, and then deploy somewhere else (and get ssl somewhere else)

**Comment by aaronkaplan** [comment]
I prefer the second option . Cloudflare man-in-the-middle SSL certificate is not something which will resonate nicely with our users/community.
@rgrp please advise on how to deploy the site on a web server that I can commission for you.

**Comment by rufuspollock** [comment]
@aaronkaplan doing option 2 will be a bit of a pain in that you will no longer get continuous deployment without some effort to do a build and then push of built html to the the web server you set up (as a) this is not something we had anticipated doing b) you'd need push access to the server I'd anticipate this is something you or moto or similar would then be doing which is probably a pain for you guys).

I therefore suggest we try something like option 1. We don't have to use cloudflare AFAICT. Other options include using AWS and cloudfront: https://news.ycombinator.com/item?id=10983245 and then e.g. http://strd6.com/2016/02/github-pages-custom-domain-with-ssltls/. Most of these are pretty simple and give you full control over the SSL etc.

**Comment by ataslim** [comment]
Thanks guys. Spoke to Aaron today and this is to be discussed a little more
during your call this week. Please let me know how that goes.

Best,
Arastoo

**Comment by rufuspollock** [comment]
@ataslim: @aaronkaplan is going to get the cloudflare account and set this up (as should be "owned" by CG here). We can help wherever necessary.

**Comment by rufuspollock** [comment]
@aaronkaplan are you ok to do this? I think it is high priority. Maybe we could help you in doing this 😄 (or take it on in some way?)

**Comment by aaronkaplan** [comment]
Let's talk on the phone / call shortly. I'll be online soon again. 

---
Mobile

**Comment by ataslim** [comment]
What was the decision here?

**Comment by aaronkaplan** [comment]
> On 27 Jan 2017, at 15:00, ataslim <notifications@github.com> wrote:
> 
> What was the decision here?

nothing yet :(

Can you please push this forward with Atomatic?

I can offer a server which will host the page and will brilliantly and nicely work with proper SSL certificates and get a "A" rating on ssllabs.com

**Comment by ataslim** [comment]
What are the implications of a switch? How easy is the switch? Any downtime? What's the cost? How does that cost compare with cloudfare?

**Comment by rufuspollock** [comment]
@ataslim switching to @aaronkaplan server is not really an option. The best solution is cloudflare I think as outlined above. We need an account on cloudflare. I can help you set this up and if we can get access we can configure for you.

**Comment by ataslim** [comment]
Ok and in your opinion would the free plan suffice for our needs?
https://www.cloudflare.com/plans/

**Comment by aaronkaplan** [comment]
Why not? Are we now tied to different cloud services? Not a good plan. 

---
Mobile

**Comment by aaronkaplan** [comment]
> On 27 Jan 2017, at 15:07, ataslim <notifications@github.com> wrote:
> 
> What are the implications of a switch? How easy is the switch? Any downtime? What's the cost? How does that cost compare with cloud fare?

From my side there are no real costs involved.
However, I'd first need to understand the workflow of pushing a page to heroku/a web server. That's an implicit requirement by using herokuapp and all the tool stack which Atomatic uses.
If the tools run on a simple web server just as well, it would be rather easy IMHO.

-> Need to discuss with Rufus.

**Comment by aaronkaplan** [comment]
> On 27 Jan 2017, at 15:07, ataslim <notifications@github.com> wrote:
> 
> What are the implications of a switch? How easy is the switch? Any downtime? What's the cost? How does that cost compare with cloud fare?

From my side there are no real costs involved.
However, I'd first need to understand the workflow of pushing a page to heroku/a web server. That's an implicit requirement by using herokuapp and all the tool stack which Atomatic uses.
If the tools run on a simple web server just as well, it would be rather easy IMHO.

**Comment by aaronkaplan** [comment]
@rufus. Regarding your comment "@ataslim switching to @aaronkaplan server is not really an option." . It is an option.

**Comment by rufuspollock** [comment]
@aaronkaplan as i noted in chat we discussed this at some length back in Dec and decided on cloudflare option. Happy to discuss again 😄

**Comment by zelima** [comment]
Moving to backlog From current milestone for now

**Comment by rufuspollock** [comment]
Clearing assignee for time being.

**Comment by aaronkaplan** [comment]
By now twitter is making fun of us...

https://twitter.com/hanno/status/826778763602051072

**Comment by rufuspollock** [comment]
FIXED. With DNS switch to cloudflare in #89 this now "just works" 😄 🎱
