### ISSUE TITLE
Serve live data out of /prod

### ISSUE THREAD

**Issue by chorsley** [cybergreen-net/pm#55]
For both ETL and aggregation, we should strictly use `/dev/` paths for preview / development sites, and `/prod/` paths for live sites.

We should set a cutover date for both the ETL and aggregation processes to begin using `/prod/` when publishing data destined for public use. From that point on, `/dev/` data should not be published to the live Cybergreen website.

I'd suggest a cutover of Monday 31 October 2016.

**Comment by rufuspollock** [comment]
@chorsley +1 on the idea. In terms of date I suggest we address this as part of a coherent planning session in the next week.

**Comment by rufuspollock** [comment]
DUPLICATE. this is now part of infrastructure issues e.g. https://github.com/cybergreen-net/infrastructure/issues/3
