### ISSUE TITLE
Aggregate data import documentation

### ISSUE THREAD

**Issue by chorsley** [cybergreen-net/pm#56]
We should document the current procedure between enriched (clean) data and import of aggregate data into RDS.

**Comment by aaronkaplan** [comment]
part of SoW. Yes. Google document for this?

**Comment by rufuspollock** [comment]
@aaronkaplan suggestion was this was documentation in the infrastructure repo - using markdown files in git. See https://github.com/cybergreen-net/infrastructure/issues/1

I suggest we leave this open in PM repo to track out highest level with work being done in that referenced issue.

**Comment by rufuspollock** [comment]
We have a diagram for this plus docs in https://github.com/cybergreen-net/aggregator
