### ISSUE TITLE
Automation required for S3 CSV -> RDS import

### ISSUE THREAD

**Issue by chorsley** [cybergreen-net/pm#57]
There is a aggregation step requiring download of the S3 CSV files to a local system, and then back up to RDS. This should be set into a standard workflow, ideally between AWS platforms.

**Comment by rufuspollock** [comment]
@chorsley agreed.

**Comment by rufuspollock** [comment]
DUPLICATE now of https://github.com/cybergreen-net/aggregator/issues/23
