### ISSUE TITLE
Risk list / taxonomy dataset (Reference)

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#6]
We already have a start on this here in our google doc: https://docs.google.com/spreadsheets/d/1PosJEjJ-exlPER8ycVwWtDdQOuCsj-41Ctiuts7qGVY/edit#gid=0

Turn this into a simple repo.

Key fields:
- id
- category
- title
- description

**Comment by aaronkaplan** [comment]
> On 26 Aug 2016, at 14:03, Rufus Pollock notifications@github.com wrote:
> 
> We already have a start on this here in our google doc: https://docs.google.com/spreadsheets/d/1PosJEjJ-exlPER8ycVwWtDdQOuCsj-41Ctiuts7qGVY/edit#gid=0
> 
> Turn this into a simple repo.
> 
> Key fields:
> 
>   • id
>   • category
>   • title
>   • description

I'd like to see that in the reference data  repo (without the counts of course).

**Comment by rufuspollock** [comment]
@aaronkaplan ok - i think one repo per dataset makes sense here so I'd suggest a single dedicated repo for this one.

**Comment by aaronkaplan** [comment]
---

Mobile

> On 26.08.2016, at 14:49, Rufus Pollock notifications@github.com wrote:
> 
> @aaronkaplan ok - i think one repo per dataset makes sense here so I'd suggest a single dedicated repo for this one.

I think we talked about subrepos, right?
I'd like to have one place reference-data/ where I can find all sub repos.

**Comment by rufuspollock** [comment]
Yes, no problem. We can easily have one place.

**Comment by chorsley** [comment]
Added this to https://github.com/cybergreen-net/reference_data/tree/master/risks based on discussion here and #24. Closing for now - please reopen if any discussion required, or edit directly.
