### ISSUE TITLE
Beta 2 stats live as main stats site

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#60]
* [x] Add custom domain on heroku using `heroku domains:add` for `stats.cybergreen.net` @zelima
* [x] Change DNS for stats.cybergreen.net to heroku domain: `cybergreen-stats.herokuapp.com.` @aaronkaplan 

Note if we want old stats site at e.g. statsold.cybergreen.net then we need to set up dns for that and change `CNAME` file on github repo.

**Comment by aaronkaplan** [comment]
@rgrp as discussed via email - can you please assign a timestamp to _when_ we switch?
The second item here depends on the first.
I need to tell the DNS guys _when_ to switch. -> time zones.

**Comment by rufuspollock** [comment]
@aaronkaplan you can initiate switch now if you want as per comment in chat channel.

**Comment by aaronkaplan** [comment]
perfect  Okay, I need to respect the JP /Tokyo time zone. It will take a bit of time. Is the custom domain `heroku domains:add`ed as noted in the checkbox above?

**Comment by zelima** [comment]
@aaronkaplan We've set the domain on Heroku and you can initiate  DNS change whenever you want

**Comment by aaronkaplan** [comment]
> On 07 Nov 2016, at 19:38, Irakli Mchedlishvili notifications@github.com wrote:
> 
> @aaronkaplan We've set the domain on Heroku and you can initiate DNS change whenever you want

Perfect! Thanks. I was not sure since the checkbox was not set yet.

Best,
a.
