### ISSUE TITLE
please inspect heroku error message

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/pm#62]
Hi, 

our scalable cloud solution seems to balk since a couple of hours.
http://stats.cybergreen.net/api/v1/count

-> Application error.

Can you please inspect and guide us on how CG can ensure lower downtimes?

**Comment by aaronkaplan** [comment]
We plan to demo the stats site tomorrow, so the API should also work.

**Comment by rufuspollock** [comment]
INVALID / DUPLICATE - open on stats-new repo ;-)
