### ISSUE TITLE
Please load the latest data [24 Nov 2016]

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/pm#68]
We are getting more and more requests by people that "our data on stats.cg.net is outdated".

Please load the newest data.
@zelima please make sure that only the latest data where all columns are non-empty are displayed on the stats site.

**Comment by chorsley** [comment]
Noted. Currently working on moving post-scan data processing scripts local, needs rewrite on scripts and make them suitable for cron-ing.

**Comment by chorsley** [comment]
Now loaded into /clean dir, and datapackage.json loaded. Please go ahead @zelima.

**Comment by zelima** [comment]
Fixed - website is live with latest data
