### ISSUE TITLE
Structure of "private" bitstore

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#7]
```
# raw source dataset provided from third parties (or logged ourselves)
/raw/
  /{dataset-name}/

# any number of other directories wanted for ETL

# final clean enriched data
/clean/
  /{dataset-name}/
     /datapackage.json
     /data/{file-name}.csv
     /data/...
```
### Clean folder dataset and file names

Dataset:

```
{riskid}-complete
# e.g.
openntp-complete
```

File names - if partitioned by time

```
{riskid}-yyyy-mm.csv
```
## Questions
- Do we structure `clean/` by risks so we have subfolders named by risk
- Do we partition clean data _files_ by time period to make them smaller. E.g. partition by month
- should `clean` always only have one set of data or do we want to support multiple runs (that might mean different processing on same raw data or using different data)?
  - My instinct is KISS and only one bunch of stuff in `clean` - if we want different stuff for internal analysis then just make `clean-{myrun}` directory

**Comment by rufuspollock** [comment]
@aaronkaplan @chorsley @kxyne let me know your thoughts esp re questions ...

**Comment by chorsley** [comment]
We should also account for live / dev data in the dir structure, e.g.

```
/dev/
  /raw/
     /{dataset-name}/
     /{dataset-name2}/
  /clean/
     /{dataset-name}/
     /{dataset-name2}/
/prod/     
  /raw/
    ...
  /clean/
    ...
```

We can also create per-developer dirs as necessary during experiments.

At all stages of our processing, we also need to explicitly set the mode which modifies production data, and have dev be the default to avoid accidental deletion and modification from errant scripts as much as possible.

**Comment by rufuspollock** [comment]
my suggestion would be to leave current layout and have that is prod and if we need `dev` then we just have `/dev/` as a space and reproduce structure inside it (as you suggest). ie.

```
/raw/
/clean/

# if we need dev
/dev/
  /raw/
  /clean/

# userspace
/user/
  /{username}/
```

**Comment by chorsley** [comment]
I'd argue for each dir structure having the same depth from the root for consistency. This lets us set an environment var to neatly set the base dir without needing to handle special cases, e.g. /{env}/raw/dataset1/, so you could have:

```
/prod/clean/dataset1/
/dev/clean/dataset1/
/user-chris/clean/dataset1/
etc
```

**Comment by rufuspollock** [comment]
@chorsley ok, good with me - though I'd imagine that pointing at the root directory for a given set of material is configurable in pretty much all clients so having it at different levels does not matter.

Re user directories: I'd still argue for simple `/user/{xyz}/`. I'd anticiapted user directories could be used for anything and need not reproduce the raw / clean structure. In addition, having just `/user/` at root makes for less directories at root which is a _good thing_ (tm) ;-)

**Comment by rufuspollock** [comment]
@chorsley i am increasingly think that raw does _not_ go inside a particular "run" subdirectory - it is independent. `raw` is a long-term archive and we store stuff there permanently independent of ETL runs.

So:

```
raw/
   logfile-name-preferably-including-risk-and-date-of-storage.csv (or .txt)

# May have subdirectories ... ?
```

**Comment by chorsley** [comment]
Does "run" in this context mean the environment, e.g. dev, prod? I'd personally want to keep that distinction still, so we can isolate a small batch of files to put in the dev directory when we're testing connectivity on a full run. 

This also lets us run testing on our collection methods, so we can try our new collection scripts writing files into dev before we unleash it on prod.

There may well be overlapping files between dev and prod, but prod will of course be the authoritative source.

I'd see the dir structure like this:

```
dev/
  raw/
     source-abc/
        logfile-yyyy-mm-dd.csv
```

**Comment by rufuspollock** [comment]
My point is that raw data we get in from partners needs to be permanently archived somewhere and this is purpose of `raw/`

Runs - whether for dev or prod may run off specific raw data and that can / should be configurable. We don't want to have to duplicate (massive) raw files into several `/dev/ /prod/ /prod-2/` directories. Remember we never write to "raw" files - they are always read from.

`raw` = our raw archive.

**Comment by chorsley** [comment]
One small distinction there - "raw" files are _mostly_ read, but must be written at least once, during the collection cycle. Collection is simple at the moment, just straight SCP file transfers, but this will get a little more involved as time goes on (extracted from emails, scraped from web pages, RSS feeds, merged from multiple sources etc).

The /dev/raw/ area is designed for prototyping experimental collection techniques and sharing new types of feed data between developers before we have tested the quality and are ready to write the final version into the primary /prod/raw/ section.  Similarly, when we need to update a collection technique, we write into /dev/raw/ for testing before unleashing it on /prod/raw/ and regenerating files.

/dev/raw/ is not designed to be a full mirror of the authoritative /prod/raw/ area - it's just what we're testing at that point in time.

**Comment by rufuspollock** [comment]
I spoke with @chorsley and we have now resolved this as follows:

```
/dev/
   /raw/
   ... # any other directories wanted for the processing scripts
   /clean/
      /data/{risk-id}-{number}.csv[.compression-suffix]

/prod/
   ... same structure as dev

/user/{username}/
```

@chorsley will implement going forwards as he writes to the S3 bucket.

We also noted that:
- it is likely that data collection demands may increase in future leading to more work around `/raw/` directory. However, this is not something that is a focus in this iteration.
- we may even move `/dev/` to separate bucket to have separate access control and reduce risk of accidental writes to `/prod/` during dev work.

**Comment by rufuspollock** [comment]
FIXED.
