### ISSUE TITLE
[ux-research] Prepare for user interviews

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#72]
* [x] Review existing user stories and epics
* [x] Interview Aaron
* [x] Prepare slide deck
* [x] Prepare notes document

**Comment by ataslim** [comment]
@rgrp can you post the interview questions?

**Comment by rufuspollock** [comment]
FIXED. Done on Monday. Here's the [Template set of questions](https://docs.google.com/presentation/d/1I0BrONK4vo4Lsi5QKS9RlenF10680Hfm-OUkoBTliiE/edit#slide=id.g344642f18_18)
