### ISSUE TITLE
Design reference data system

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#74]
Discussed that we would plan this at tech team meeting 2 weeks ago

* [x] Structure of a reference dataset
* [x] Where we store them
* [x] Usage in Data Warehouse
* [ ] <del>Management process</del> - not relevant for now

Actions arising

* [x] Write up this process in this pm repo in `/doc/reference-data.md`
* [x] Identify next steps - see #76

**Comment by rufuspollock** [comment]
Most of this now done - see [Slide 21 onwards](https://docs.google.com/presentation/d/14-tJ3Ca0qstmgwLENQh5jflChB4MxZoUkA96fFoqGbU/edit#slide=id.g13c7436e56_1_29)

Next steps is to convert these plans into:

* markdown documentation either in this repo or infrastructure repo.
* identify next steps

**Comment by zelima** [comment]
instructions for seting up ref-data repos added https://github.com/cybergreen-net/pm/blob/master/docs/reference-data.md

**Comment by rufuspollock** [comment]
FIXED. Modulo a few tidy ups suggested in comments in https://github.com/cybergreen-net/pm/commit/788da41644321cc490e67783dcf3cb17ac61940c
