### ISSUE TITLE
Load Latest Data (22 Dec 2016)

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#78]
@aaronkaplan creating this issue to track plan to do a latest load ...

Aside for @zelima: how complex is it to push this data to both production and staging? If it is complex i suggest we move staging to production *now* - but that is another issue to track.

**Comment by zelima** [comment]
@rufuspollock No problem pushing data to both...

**Comment by zelima** [comment]
FIXED newest data is live for both stages.
