### ISSUE TITLE
Stats Portal Report (with improved data sources) Dec 2016

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#81]
[Draft doc](https://docs.google.com/document/d/1uucQLCegvVYr0vjfKXIE1_QN08G2-WXPBcAJdnKHbWw/edit#)

* [x] Data improvement
* [x] ETL
* [x] Aggregator
* [x] Reference data
* [x] Stats portal (frontend) @zelima + @rufuspollock

**Comment by rufuspollock** [comment]
@zelima only thing remaining here IMO is for you to add screenshots of site in section marked. We can only do this once data refresh and final tech changes are done.

**Comment by zelima** [comment]
FIXED https://docs.google.com/document/d/1uucQLCegvVYr0vjfKXIE1_QN08G2-WXPBcAJdnKHbWw/edit#
