### ISSUE TITLE
Overall docs for portal 

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#82]
This is ultimately due in March. Work now should be on intermediate versions.

*  [x] Short [sysadmin] user manual - this can consist of various READMEs - ATOMATIC
   * Mainly READMEs for now - @zelima @rufuspollock
* [ ] Metrics description
  * [ ] Metrics working paper from November @aaronkaplan 
  * [x] Screenshots / summaries showing implementation in code @zelima 
* [x] “How to” guide on use of CyberGreen stats portal
  * A slide-deck walkthrough (stats portal won't have a "guide" per se since it should be usable without docs) ?? @shiweiart @zelima @ataslim 

**[Draft google doc for this](https://docs.google.com/document/d/1Y4xETmEJPj-slpl0aeMV5g5HKOflduvzLrdH7c9HgIg/edit)**

**Comment by zelima** [comment]
@rufuspollock @ataslim doc is updated https://docs.google.com/document/d/1Y4xETmEJPj-slpl0aeMV5g5HKOflduvzLrdH7c9HgIg/edit#heading=h.8t12zkka3asm

**Comment by rufuspollock** [comment]
@aaronkaplan @ataslim  from our end this is now complete. I think the only thing missing would be the metrics working paper if you want to include that. I'm unassigning us from this is issue to reflect we are complete at our end 😄

**Comment by rufuspollock** [comment]
FIXED. Assume @ataslim and @aaronkaplan did their part 😄
