### ISSUE TITLE
ASN page on stats site

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/pm#9]
- [ ] First pass design for page
- [ ] Implement first pass
## Aaron thoughts

Below are some ramblings/thoughts on the ASN visualisation:

IMHO this is a bit tricky because there are so many ASNs to display.
I also created a country2asn CSV file in the github reference-data/ repo (github.com -> cyber-green/reference-data). Hope it helps. This would be one possible way to make a map of the ASNs (some kind of heat map)? But of course, I am open to better ideas.

Since we have thousands of ASNs per country often, the real question is - how do we display this so that it becomes meaningful?

We could of course also make a very long ranking table (but I highly suggest that we have some kind of interactive JavaScript search/drill-down-field which allows you to search by ASN and AS name)

Please also note the stat.ripe.net interface: here you can query the AS name from the ASN (AS number).
That's also very practical.

Another thing: tree maps?

**Comment by chorsley** [comment]
I love me some tree maps, +1 to try that first :) There are some great implementations out there that allow dynamic filtering (e.g. by cc) and zooming, as well as drilling into underlying data.

**Comment by rufuspollock** [comment]
FIXED in terms of a first pass. http://cybergreen-stats.herokuapp.com/place/united-kingdom/asn/4585458
