### ISSUE TITLE
Final Documentation on CyberGreen Statistics Portal

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/pm#93]
“How to” guide on use of CyberGreen stats portal

[Google doc](https://docs.google.com/document/d/1D96nWl0_kcAjGa1IlS3ARwiYX0jUMeQYPDOpOdvnEDc/edit#)

## Tasks

For each page

- provide a small description of what page is for, what it shows and what may next steps be
- include screen shots

**Comment by zelima** [comment]
Mostly FIXED. we may need to updated with latest screenshots if needed on the deadline date

**Comment by rufuspollock** [comment]
FIXED. @ataslim can you review and reopen if you need anything more here
